"""Generate the C tables using the pinned Python 3.11 Unicode behavior."""
import sys,unicodedata
from pathlib import Path
if sys.version_info[:2]!=(3,11):raise SystemExit('Run with Python 3.11')
root=Path(__file__).resolve().parents[1]/'src'
def ranges(values):
 result=[]
 for v in values:
  if result and v==result[-1][1]+1:result[-1][1]=v
  else:result.append([v,v])
 return result
def table(name,rows,width):
 return 'static const uint32_t '+name+'[]['+str(width)+']={\n'+''.join('{'+','.join(map(str,row))+'},\n' for row in rows)+'};\n'
low=[];up=[];alpha=[];cased=[];ignorable=[]
for code in range(0x110000):
 c=chr(code);lo=c.lower();hi=c.upper()
 if lo!=c:low.append([code,*map(ord,lo),*([0]*(2-len(lo)))])
 if hi!=c:up.append([code,*map(ord,hi),*([0]*(3-len(hi)))])
 if c.isalpha():alpha.append(code)
 if lo!=hi:cased.append(code)
 if ('AΣ'+c+' A').lower()[1]=='ς' and ('AΣ'+c+'A').lower()[1]=='σ':ignorable.append(code)
header='/* Generated by scripts/generate_unicode.py; Unicode '+unicodedata.unidata_version+'. */\n'
(root/'unicode_data.h').write_text(header+table('lower_map',low,3)+table('alpha_ranges',ranges(alpha),2))
(root/'uppercase_data.h').write_text(header+table('upper_map',up,4))
(root/'case_data.h').write_text(header+table('cased_ranges',ranges(cased),2)+table('ignorable_ranges',ranges(ignorable),2))
