"""Generate native LingPatLab constants from the pinned source and reference runtime."""
import argparse,ast,hashlib,json,shutil,sys,unicodedata
from pathlib import Path
import unicodedata2
ROOT=Path(__file__).resolve().parents[1]
p=argparse.ArgumentParser();p.add_argument('--source',type=Path,default=ROOT/'.reference/lingpatlab');a=p.parse_args()
source=a.source/'lingpatlab'
site=Path(sys.prefix)/('Lib/site-packages' if sys.platform=='win32' else 'lib/python3.11/site-packages')
assert sys.version_info[:2]==(3,11)
assert unicodedata.unidata_version=='14.0.0'
def constants(path):
 result={}
 for n in ast.parse(path.read_text(encoding='utf-8')).body:
  if isinstance(n,(ast.Assign,ast.AnnAssign)):
   name=n.targets[0].id if isinstance(n,ast.Assign) else n.target.id
   try:result[name]=ast.literal_eval(n.value)
   except (ValueError,TypeError):pass
 return result
values={}
for path in sorted((source/'tokenizer/dto').glob('*.py')):
 values.update(constants(path))
for kind in ['people','topic']:
 for k,v in constants(source/f'analyze/dmo/{kind}_sequence_extractor.py').items():values[kind+'_'+k]=v
for kind in [1,2]:
 for k,v in constants(source/f'analyze/dto/text_summary_prompts_{kind}.py').items():values[f'prompt{kind}_'+k]=v
values['pronouns']={'1':['i','me','my','mine','myself','we','us','our','ourselves'],'2':['you'],'3':['she','her','he','him','it','they','them']}
lines=['/* Generated by scripts/generate_lingpatlab_data.py. */','typedef struct { const char *name, *json; } LpConstant;','static const LpConstant lp_constants[] = {']
for k,v in values.items():lines.append('{'+json.dumps(k)+','+json.dumps(json.dumps(v,ensure_ascii=True,separators=(',',':')))+'},')
lines.append('};\n')
(ROOT/'src/lingpatlab_data.h').write_text('\n'.join(lines))
hashes=[]
for path in sorted((site/'wordnet_lookup/hs').glob('h_*.py')):
 tree=ast.parse(path.read_text());node=next(n for n in tree.body if isinstance(n,ast.Assign))
 hashes.extend(path.stem[2:]+v for v in ast.literal_eval(node.value.args[0]))
hashes=sorted(set(hashes))
(ROOT/'src/wordnet_data.h').write_text('/* WordNet lookup 1.3.4 hashes; generated by scripts/generate_lingpatlab_data.py. */\nstatic const char lp_wordnet_hashes[][33] = {\n'+''.join(json.dumps(x)+',\n' for x in hashes)+'};\n')
def ranges(values):
 result=[]
 for v in values:
  if result and v==result[-1][1]+1:result[-1][1]=v
  else:result.append([v,v])
 return result
lines=['/* Python 3.11 Unicode 14.0, unicodedata2 '+unicodedata2.unidata_version+'; generated. */']
for name,predicate in [('numeric',str.isnumeric),('upper',str.isupper),('punct',lambda c:unicodedata2.category(c).startswith('P'))]:
 rows=ranges(i for i in range(0x110000) if predicate(chr(i)))
 lines.append('static const uint32_t lp_'+name+'_ranges[][2] = {\n'+''.join('{%d,%d},\n'%tuple(x) for x in rows)+'};')
lines.append('typedef struct { uint32_t code; const char *ascii; } LpAscii;\nstatic const LpAscii lp_ascii_map[] = {')
for code in range(128,0x110000):
 s=unicodedata.normalize('NFKD',chr(code)).encode('ascii','ignore').decode()
 if s:lines.append('{'+str(code)+','+json.dumps(s)+'},')
lines.append('};\n');(ROOT/'src/lingpatlab_unicode.h').write_text('\n'.join(lines))
vendor=ROOT/'vendor/wordnet-lookup';vendor.mkdir(exist_ok=True)
shutil.copy2(site/'wordnet_lookup-1.3.4.dist-info/licenses/LICENSE',vendor/'LICENSE')
report={'lingpatlab_revision':'2ed920f1bc7e57d8c74b5b35a54e90f2b7f8ed71','lingpatlab_version':'1.1.1','wordnet_lookup_version':'1.3.4','wordnet_hashes':len(hashes),'unicode':unicodedata.unidata_version,'punctuation_unicode':unicodedata2.unidata_version,'files':{}}
for name in ['lingpatlab_data.h','wordnet_data.h','lingpatlab_unicode.h']:
 path=ROOT/'src'/name;report['files']['src/'+name]=hashlib.sha256(path.read_bytes()).hexdigest()
(ROOT/'vendor/lingpatlab/data-manifest.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps(report,indent=2))
